version: '3.7'

services:
   car:
     image: car
     container_name: car
     build:
       context: .
       dockerfile : Dockerfile
     restart: always
     ports:
      - 8080:8080
     depends_on:
      - maria_db
   maria_db:
      image: mariadb
      container_name : dbtest
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_DATABASE: test
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root